# Homebrew Bundle file for this dotfiles repo.
#
# Installs every Homebrew dependency the dotfiles expect. Run it directly with:
#     brew bundle --file=Brewfile
# or let ./install.sh do it (plus the non-brew bootstrap) for you.
#
# NOTE: nvm is intentionally NOT here — the dotfiles expect it at ~/.nvm
# (its official installer), not the Homebrew layout. install.sh handles it.

tap "thoughtbot/formulae"

# Dotfile manager (symlinks these files into $HOME)
brew "rcm"

# Shell prompt + highlighting referenced in zshrc
brew "oh-my-posh"
brew "zsh-syntax-highlighting"

# Fuzzy finder (zshrc sources ~/.fzf.zsh, generated by fzf's install script)
brew "fzf"

# Terminal session/agent multiplexer — autostarts from zshrc (herdr.dev)
brew "herdr"

# Python version manager (init'd in zshrc; node is handled by nvm at ~/.nvm)
brew "pyenv"

# Used by zsh completions and the git ctags hooks
brew "the_silver_searcher"   # provides `ag` (zsh/completion/_ag)
brew "universal-ctags"       # git_template ctags hooks

# Git + large file support (gitconfig has an lfs filter)
brew "git"
brew "git-lfs"

# Nerd Font for oh-my-posh glyphs. Casks are macOS-only; on Linux install
# "Meslo LG Nerd Font" into ~/.local/share/fonts and run fc-cache -f.
cask "font-meslo-lg-nerd-font" if OS.mac?
